// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzijgdWRCHFnx6r2YbsoA0GwRFM_qT13Q',
    appId: '1:242425400408:web:ec11faccddc705ad2c0e2d',
    messagingSenderId: '242425400408',
    projectId: 'userdata-15b42',
    authDomain: 'userdata-15b42.firebaseapp.com',
    storageBucket: 'userdata-15b42.appspot.com',
    measurementId: 'G-T7VTWS1C9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsJjPijgtSScegn5NQxXFtIv82pas2tMI',
    appId: '1:242425400408:android:1b9904da1c6847ba2c0e2d',
    messagingSenderId: '242425400408',
    projectId: 'userdata-15b42',
    storageBucket: 'userdata-15b42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlI7EDTt9CdjsXS16iV-nNyPrWF77F9BM',
    appId: '1:242425400408:ios:280040a1dbe435ad2c0e2d',
    messagingSenderId: '242425400408',
    projectId: 'userdata-15b42',
    storageBucket: 'userdata-15b42.appspot.com',
    iosBundleId: 'com.example.useradddata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlI7EDTt9CdjsXS16iV-nNyPrWF77F9BM',
    appId: '1:242425400408:ios:6bb2e594799fba012c0e2d',
    messagingSenderId: '242425400408',
    projectId: 'userdata-15b42',
    storageBucket: 'userdata-15b42.appspot.com',
    iosBundleId: 'com.example.useradddata.RunnerTests',
  );
}
